### ISSUE TITLE
Resource leak in SimpleBackupStore

### ISSUE THREAD

**Issue by darogers** [eclipse-equinox/p2#116]
The call to Files.list() in org.eclipse.equinox.internal.p2.touchpoint.natives.SimpleBackupStore.backupDirectory(File) should be wrapped in a try-with-resources statement in order to release the file handler earlier on Windows.  This isn't technically a resource leak since the handle will be lazily released at some later time, but it does cause problems on some Windows systems.

The problem:
The directory being listed is deleted(using Files.delete(Path)) shortly after this call.  In some circumstances, when a file handle is open to a file/directory, the delete is handled as a request, it's not immediately deleted.  When that happens, subsequent accesses to that location to update/install new content fails.  When using the Windows procmon utility, this error is shown as DELETE PENDING.  The delete folder remains inaccessible until the handle is released at some indeterminate time, or until the application is shut down.

The circumstances that reveal this problem:
In Windows 10 builds somewhere between 17134 and 18363, the Windows delete semantics changed to enable FILE_DISPOSITION_POSIX_SEMANTICS by default.  And this apparently only applies to NTFS formatted drives.  From the Microsoft documentation:
"When FILE_DISPOSITION_POSIX_SEMANTICS is not set, a file marked for deletion is not actually deleted until all open handles for the file have been closed and the link count for the file is zero. When FILE_DISPOSITION_POSIX_SEMANTICS is set, the link is removed from the visible namespace as soon as the POSIX delete handle has been closed, but the file's data streams remain accessible by other existing handles until the last handle has been closed."

So, for Windows 10 builds before posix semantics were the default, or installs running on an exFAT formatted drive, feature updates with native touchpoints can fail with the following signature:

!MESSAGE An error occurred while uninstalling
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2022-07-18 16:04:51.930
action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction).
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2022-07-18 16:04:51.930
!MESSAGE File is not a directory: C:\path\to\directory
!STACK 0
java.lang.IllegalArgumentException: File is not a directory: C:\path\to\directory
    at org.eclipse.equinox.internal.p2.touchpoint.natives.SimpleBackupStore.backupDirectory(SimpleBackupStore.java:271)
    at org.eclipse.equinox.internal.p2.touchpoint.natives.LazyBackupStore.backupDirectory(LazyBackupStore.java:44)
    at org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction.cleanupzip(CleanupzipAction.java:121)
    at org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction.execute(CleanupzipAction.java:34)
    at org.eclipse.equinox.internal.p2.engine.ParameterizedProvisioningAction.execute(ParameterizedProvisioningAction.java:42)
    at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:186)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:99)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
    at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:181)
    at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
    at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:188)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by akurtakov** [comment]
As you have investigated the issue already, what do you think about providing a PR doing so?

**Comment by merks** [comment]
This was fixed by

https://github.com/eclipse-equinox/p2/pull/68

https://github.com/eclipse-equinox/p2/blame/f486aa5cd0f57fadb6d536a2888dd7d6303598c0/bundles/org.eclipse.equinox.p2.touchpoint.natives/src/org/eclipse/equinox/internal/p2/touchpoint/natives/SimpleBackupStore.java#L275
