### ISSUE TITLE
Can't launch Eclipse after latest update

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-equinox/p2#24]
Moving from [Bug 579334](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579334) - Can't launch Eclipse after latest update

Running eclipse on Arch linux. After latest update can't launch it. Log:

!SESSION Sat Mar 19 20:06:30 EDT 2022 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2022-03-19 20:06:30.692
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.600.v20220207-1403.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2022-03-19 20:06:30.711
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

same problem on Linux Mint 20.3

!SESSION Wed Mar 30 09:18:11 CDT 2022 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2022-03-30 09:18:11.278
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.600.v20220207-1403.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2022-03-30 09:18:11.291
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

I tried ./eclipse -clean with same result.

Attachment from Jeff jones
[previous log.zip.zip](https://github.com/eclipse-equinox/equinox.framework/files/8386656/previous.log.zip.zip)

**Comment by merks** [comment]
Perhaps the stuff that is being done by AgentImpl should be moved to p2.  I'm not sure that's feasible though.

**Comment by merks** [comment]
I'll close because this isn't caused by p2 but an unfortunately sequence of updates in Oomph, one of which disables Oomph's p2 extensions.
