### ISSUE TITLE
Existing eclipse plugin missing after installing an update site

### ISSUE THREAD

**Issue by pnickoll** [eclipse-equinox/p2#241]
Hi,

After installing my update site into eclipse one (or more) of eclipse plugins are no longer considered installed. 

The error I see after installing my update site is shown below. After some investigation it appears that the jakarta.enterprise.cdi bundle which exports the package javax.enterprise.context (which is shown as missing in the OSGi error) is no longer installed. On the OSGi console when I perform an ss I don't see it there (but I do before I install my update site). It also does not appear in configuration/org.eclipse.equinox.simpleconfigurator/bundles.info (but it did prior to my install). The file itself is still in the plugins directory.

This used to work in previous Eclipse releases and stopped working in Eclipse 2022-12 and 2023-03. It worked in Eclipse 2022-09 and earlier ones.

To test this you can install IBM Liberty Developer Tools 22.2 from the Eclipse market place on either Eclipse 2022-12 or Eclipse 2023-03. Doing this it will detect problems and will offer to only install part of the update site. I don't believe that is the cause as the next version of Liberty Developer Tools that is in development now appears to install OK yet still has the missing jakarta.enterprise.cdi bundle.

Also FYI I have tried restarting with the --clean flag. We are using the JEE eclipse package and have seen this error on both Windowws and Linux. 

Has the p2 code changed in that time period in a way that could effect this? Is this any diagnostic information I can gather?

```
!ENTRY org.eclipse.jst.server.preview.adapter 4 0 2023-03-28 18:32:00.682
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jst.server.preview.adapter [529]
  Unresolved requirement: Require-Bundle: org.eclipse.wst.server.preview; bundle-version="[1.2.0,2.0.0)"
    -> Bundle-SymbolicName: org.eclipse.wst.server.preview; bundle-version="1.2.100.v202211091907"; singleton:="true"
       org.eclipse.wst.server.preview [803]
         Unresolved requirement: Require-Bundle: org.eclipse.jetty.plus; bundle-version="[10.0.1,11.0.0)"
           -> Bundle-SymbolicName: org.eclipse.jetty.plus; bundle-version="10.0.13"
              org.eclipse.jetty.plus [430]
                Unresolved requirement: Import-Package: org.eclipse.jetty.webapp; version="[10.0.13,11.0.0)"
                  -> Export-Package: org.eclipse.jetty.webapp; bundle-symbolic-name="org.eclipse.jetty.webapp"; bundle-version="10.0.13"; version="10.0.13"; uses:="javax.servlet,org.eclipse.jetty.security,org.eclipse.jetty.server,org.eclipse.jetty.server.handler,org.eclipse.jetty.server.session,org.eclipse.jetty.servlet,org.eclipse.jetty.util,org.eclipse.jetty.util.annotation,org.eclipse.jetty.util.component,org.eclipse.jetty.util.resource,org.eclipse.jetty.xml"
                     org.eclipse.jetty.webapp [436]
                       Unresolved requirement: Require-Capability: osgi.extender; filter:="(osgi.extender=osgi.serviceloader.processor)"
                         -> Provide-Capability: osgi.extender; osgi.extender="osgi.serviceloader.processor"; version:Version="1.0.0"
                       Unresolved requirement: Require-Capability: osgi.extender; filter:="(osgi.extender=osgi.serviceloader.registrar)"
                         -> Provide-Capability: osgi.extender; osgi.extender="osgi.serviceloader.registrar"; version:Version="1.0.0"
                Unresolved requirement: Import-Package: javax.transaction; version="1.1.0"
                  -> Export-Package: javax.transaction; bundle-symbolic-name="jakarta.transaction-api"; bundle-version="1.3.3"; version="1.3.3"; uses:="javax.interceptor,javax.transaction.xa,javax.enterprise.util,javax.enterprise.context"
                     jakarta.transaction-api [28]
                       Unresolved requirement: Import-Package: javax.enterprise.context
                Unresolved requirement: Require-Capability: osgi.extender; filter:="(osgi.extender=osgi.serviceloader.registrar)"
                  -> Provide-Capability: osgi.extender; osgi.extender="osgi.serviceloader.registrar"; version:Version="1.0.0"
         Unresolved requirement: Require-Bundle: org.eclipse.jetty.webapp; bundle-version="[10.0.1,11.0.0)"
           -> Bundle-SymbolicName: org.eclipse.jetty.webapp; bundle-version="10.0.13"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by akurtakov** [comment]
Is this still an issue with 2023-06 RCs? FWIW this doesn't look like an issue with p2 but rather issue with some p2 site. If you believe this is p2 bug please share small reproducer.

**Comment by pnickoll** [comment]
It turns out this was due to an eclipse feature having a dependency removed see https://bugs.eclipse.org/bugs/show_bug.cgi?id=582183 . I think that should fix the probelm

**Comment by mickaelistria** [comment]
The `Unresolved requirement: Import-Package: javax.enterprise.context` seems to illustrate that p2 did uninstall things too greedily.
