### ISSUE TITLE
Cannot install Eclipse tests framework in recent integration builds, invalid URI scheme file

### ISSUE THREAD

**Issue by trancexpress** [eclipse-equinox/p2#262]
For some time now, I've been getting the following error when trying to install the Eclipse test framework in an SDK integration build.

E.g. download a recent integration build: https://download.eclipse.org/eclipse/downloads/drops4/I20230507-1800/download.php?dropFile=eclipse-SDK-I20230507-1800-linux-gtk-x86_64.tar.gz
Then try to install the corresponding test framework: https://download.eclipse.org/eclipse/downloads/drops4/I20230507-1800/download.php?dropFile=eclipse-test-framework-I20230507-1800.zip

Observe an error dialog and logged exception:

```
java.lang.IllegalArgumentException: invalid URI scheme file
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Utils.java:286)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(HttpRequestBuilderImpl.java:82)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:71)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:43)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.lambda$9(AuthorityChecker.java:253)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3064)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.gatherCertificates(AuthorityChecker.java:251)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.getCertificates(AuthorityChecker.java:244)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.start(AuthorityChecker.java:124)
	at org.eclipse.equinox.internal.p2.engine.phases.Collect.completePhase(Collect.java:97)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:181)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:188)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by trancexpress** [comment]
I don't know if this is a P2 problem or a problem with the artifacts for the test framework. How to validate its not the latter?

**Comment by merks** [comment]
I’ll have a look tomorrow.  Can you tell me exactly which URI you used so that I can reproduce the in a debug launch?

**Comment by trancexpress** [comment]
> I’ll have a look tomorrow. Can you tell me exactly which URI you used so that I can reproduce the in a debug launch?

The jar URI for the update site (from the test framework archive) is:

```
jar:file:/data/eclipses/eclipseSDK_428_m20230507/eclipse-test-framework-I20230507-1800.zip!/
```

Or do you mean something else?

**Comment by merks** [comment]
Yes, that's exactly what I meant.  I could reproduce the problem and it was easy to fix, so I'll merge later when the verification build is done.  

Thanks for reporting the issue!

**Comment by trancexpress** [comment]
Sounds great, thanks!
