### ISSUE TITLE
NPE in TrustAuthorityDialog

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-equinox/p2#270]
* have an Oomph setup based on Latest (2023-06)
* have http://update.eclemma.org in that setup, and execute it.
* uncheck the eclemma node in the upcoming trust dialog:
![image](https://github.com/eclipse-equinox/p2/assets/406876/fbcabd47-b9ac-4e0d-9196-60afd8a40041)

Leads to NPE:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.viewers.TreeNode.getChildren()" because "treeNode" is null
	at org.eclipse.equinox.internal.p2.ui.dialogs.TrustAuthorityDialog.getAllChildren(TrustAuthorityDialog.java:823)
	at org.eclipse.equinox.internal.p2.ui.dialogs.TrustAuthorityDialog.getAllChildren(TrustAuthorityDialog.java:818)
	at org.eclipse.equinox.internal.p2.ui.dialogs.TrustAuthorityDialog.lambda$3(TrustAuthorityDialog.java:260)
	at org.eclipse.jface.viewers.CheckboxTreeViewer$1.run(CheckboxTreeViewer.java:168)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.fireCheckStateChanged(CheckboxTreeViewer.java:165)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.handleSelect(CheckboxTreeViewer.java:295)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1205)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:263)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:421)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.equinox.internal.p2.ui.ValidationDialogServiceUI.lambda$18(ValidationDialogServiceUI.java:467)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```
The NPE is caused by getParent() returning null in https://github.com/eclipse-equinox/p2/blob/aa4840ff474976da781a066cabb4eb5029f2790c/bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustAuthorityDialog.java#L252.

The eclemma update site lead to similar trouble at other places before: https://bugs.eclipse.org/bugs/show_bug.cgi?id=581911. @merks might be able to tell whether the eclemma update site should even be listed here in the dialog. I myself don't really know if we need to fix the event handler or if we need to avoid having the update site being shown there.

**Comment by merks** [comment]
In the latest version of the installer (with latest p2), I expect it to look like this:

![image](https://github.com/eclipse-equinox/p2/assets/208716/0fec65a3-8d94-4aaa-a4e4-dfd36d008984)

It also looks like this in the IDE

![image](https://github.com/eclipse-equinox/p2/assets/208716/9772d05c-4d19-452e-87cf-c83f0007ce06)

The site itself does not support redirection to https so I'm not sure how to reproduce this problem.

Are you really doing this from an IDE where the latest is already installed?

**Comment by merks** [comment]
The fact that you see https in the dialog suggests you are using a version of Oomph before this commit:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=12056d3aa48c74715ebbd99b42e47bc45937136d

Before that commit, https redirection would fail, but then a cached version of the http URI content would be used making it look like it succeeded.

So if you have an older version of Oomph you probably also have an older version of p2...

Please try to reproduce this with the m3 versions of both.

**Comment by Bananeweizen** [comment]
You were right, Ed. The installation was basically M2. By using the normal Eclipse update mechanism without Oomph, I was then able to upgrade Oomph and P2, and haven't been able to reproduce the issue since then. Therefore I'll close the issue.
I'm still not sure if people using existing "latest release" installations will be able to upgrade to the June version if they also have some http-only update site. In my restricted understanding of the issue, they would need the newer version of Oomph to avoid the problem, but they cannot upgrade to that newer version of Oomph using the old one contained in their installation. They would be able to upgrade using Help>Check for updates, but they might miss that alternative.

**Comment by merks** [comment]
Older versions (2023-03 release) do not do http -> https redirection (they just log warnings) so people will be able to update using http.  Of course they generally won't have any < 2023-06 m3 bugs either.   After they've upgraded, it's still possible to enable http usage but you have to do so explicitly:

https://www.eclipse.org/eclipse/news/4.28/platform.php#Security
