### ISSUE TITLE
P2 password dialog causes deadlock / authentication failed

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#330]
Today I tried to do some tests with a password protected P2 site but Eclipse complained and even if the username/password seems to be correct it fails to get the password:

```
!MESSAGE To avoid deadlock while executing Display.syncExec() with argument: org.eclipse.equinox.internal.p2.ui.ValidationDialogServiceUI$$Lambda$1289/0x0000000801514000@4e7c1c14, thread Worker-4: Resolving "references" target definition will interrupt UI thread.
!SUBENTRY 1 org.eclipse.ui 4 4 2023-09-21 16:17:37.117
!MESSAGE Worker-4: Resolving "references" target definition thread is an instance of Worker or owns an ILock
!STACK 0
java.lang.IllegalStateException: Call stack for thread Worker-4: Resolving "references" target definition
	at java.management@17.0.2/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@17.0.2/sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:485)
	at org.eclipse.ui.internal.UILockListener.reportInterruption(UILockListener.java:214)
	at org.eclipse.ui.internal.UILockListener.interruptUI(UILockListener.java:180)
	at org.eclipse.ui.internal.PendingSyncExec.waitUntilExecuted(PendingSyncExec.java:92)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:142)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at org.eclipse.equinox.internal.p2.ui.ValidationDialogServiceUI.getUsernamePassword(ValidationDialogServiceUI.java:343)
	at org.eclipse.equinox.internal.p2.repository.Credentials.forLocation(Credentials.java:219)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:109)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.handleRemoteIndexFile(AbstractRepositoryManager.java:738)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadIndexFile(AbstractRepositoryManager.java:732)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:674)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getQueryableMetadata(P2TargetUtils.java:1018)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.getRootIUs(IUBundleContainer.java:768)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getRootIUs(P2TargetUtils.java:1506)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:1066)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:828)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:404)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:651)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by merks** [comment]
Your comment suggests that you were actual able to enter credentials?  Or?  Is this perhaps an issue with the new ECF implementation not using the credentials correctly?

**Comment by laeubi** [comment]
I can enter the credentials but they seem not having any effect, I made sure that the credentials are correct but still P2 complains it can't authenticate.

My first guess was that due to the interruption P2 might not be able to get the dialog result but for sure it *might* be that ECF is not able to handle them.

**Comment by merks** [comment]
Is there some site/way to reproduce this?  I can try to help...

I tested accessing an Oomph setup in a private git repository accessible via a GitHub Personal Access Token.  That is using the ECFURIHandler which is using the new ECF implementation, so there doesn't appear to be anything fundamental wrong...

**Comment by iloveeclipse** [comment]
Can you post **full** error log (I miss the UI thread stack)?

**Comment by laeubi** [comment]
Here is how to reproduce this:

I have a target file with the following content:
```
<target name="pps">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
			<repository location="https://sslsites.de/pps.laeubi-soft.de/"/>
			<unit id="com.microsoft.sqlserver.mssql-jdbc" version="0.0.0"/>
		</location>
	</locations>
</target>
```

If I open this with I get a prompt asking for username + password (here: `test` / `test`), enter the credentials and then get be prompted again (and again and again) then the target can not be loaded:
![grafik](https://github.com/eclipse-equinox/p2/assets/1331477/bd178585-b775-41e3-9e2f-33dd03eb47c4)


No i go to https://sslsites.de/pps.laeubi-soft.de/p2.index in a browser and getting asked for username+passwort, enter the credentials and see I can access the file.

@iloveeclipse strange enough now I can't find the stacktrace anymore in the logfile, though the problem persist, it might be that I'm now using a stripped down update-site.

**Comment by merks** [comment]
Very good!  I will try to find time soon **after** I get the target platform updated to Orbit m1, e.g., with the latest version of ant, to debug this:

I can reproduce the problem in the repository explorer:

![image](https://github.com/eclipse-equinox/p2/assets/208716/f330ad13-4bc3-4e33-97fd-8a41ec7a3888)

![image](https://github.com/eclipse-equinox/p2/assets/208716/6dec625a-0324-4ac5-80f7-104f3394e7eb)

But only with the new implementation.  It loads fine in a 2023-09 installation:

![image](https://github.com/eclipse-equinox/p2/assets/208716/23a97164-72f3-41f8-bd04-37671d79b2c5)

So this does appear to be a regression...

This is one major concern I have with the new implementation.  Who exactly will be tracking down all the new problems, e.g., horrible firewall password problem?

**Comment by laeubi** [comment]
> This is one major concern I have with the new implementation. Who exactly will be tracking down all the new problems, e.g., horrible firewall password problem?

The only thing that works is that people test their workflows, report problems and provide reproducers. Even though I initially though it was a different problem because of the stack-trace.

**Comment by merks** [comment]
We have the reproducer,  the question was, **who tracks the problem down**?  I had a quick look; it seems to me the information disappears into a black hole at this point where the information is stored, but never used:

![image](https://github.com/eclipse-equinox/p2/assets/208716/6099bfec-3f73-475d-9f34-b1098e288ce4)

So who fixes that?

I'm just trying to determine where responsibility lies because I get the sense that all of this ends up on my plate even though I never ordered this dish...

**Comment by laeubi** [comment]
> I'm just trying to determine where responsibility lies

I think https://github.com/eclipse-equinox#contributing applies here, so if you can help its great if not its not you to blame here... I probably will also try to take a look so at least its useful to share anything one find out already.

**Comment by scottslewis** [comment]
Is there any information about this update site:  https://sslsites.de/pps.laeubi-soft.de/p2.index that anyone has?  e.g. is it using a proxy, if so what type of proxy+config? , also what kind of https server is it?  and how it's configured wrt ssl?

From @merks above it looks like the httpclient5 (9-2023) works, correct?

Also for me to catch up:  Is there an integration release of Eclipse that is using javahttpclient provider?  If so, which one?

**Comment by scottslewis** [comment]
Here are some insights.

It appears that when accessing https://sslsites.de/pps.laeubi-soft.de/ for HttpClientFileSystemBrowser (HEAD request to get directory information) that server asks for Basic authentication.

The class:  ECFHttpClientFactory (a separate instance of this class in both httpclient5 provider and javahttpclient provider) sets up the config for a new request by calling the newRequestConfig method.
 
In the httpclient5 newRequestConfig are these lines:

`		Collection<String> preferredAuthSchemes = allowNTLMAuthentication ? DEFAULT_PREFERRED_AUTH_SCHEMES : DEFAULT_PREFERRED_AUTH_SCHEMES_NO_NTLM;
		builder.setProxyPreferredAuthSchemes(preferredAuthSchemes);
		builder.setTargetPreferredAuthSchemes(preferredAuthSchemes);
`

Which sets up the auth schemes (basic, digest, ntlm).   But there is nothing like the above for the javahttpclient.ECFHttpClientFactory.newRequestConfig method.   There are actually the constant string arrays DEFAULT_PREFERRED_AUTH_SCHEMES  and DEFAULT_PREFERRED_AUTH_SCHEMES_NO_NTLM as class constants, but the are *unused* in the java httpclient provider newRequestConfig method.

The problem is, the HttpRequest.Builder in javahttpclient does not have either of the setProxyPreferredAuthSchemes nor the setTargetPreferredAuthSchemes methods so I don't know how the auth schemes are set in for javahttpclient...but I suspect that however that is done in the javahttpclient needs to be done in the javahttpclient newRequestConfig implementation.

@laeubi do you know how the preferred auth schemes are set in the java httpclient?

**Comment by laeubi** [comment]
@scottslewis there are two possible ways to use:

1. You can set an [Authenticator](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/Authenticator.html) that is then asks for credentials when the server request them: https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Builder.html#authenticator(java.net.Authenticator)
2. You can do preemptive auth if you know that the request will require an authentication ([Tycho do it here](https://github.com/eclipse-tycho/tycho/blob/master/p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/transport/MavenAuthenticator.java#L132))

I don't know what matches best the ECF API, but the second should work best if you already know the password in advance from the context as otherwise the server might be queried twice (first without credentials, then the Authenticator is asked and then the request is done again).

**Comment by merks** [comment]
@scottslewis 

I can confirm that this changes addresses the basic-auth problem:

![image](https://github.com/eclipse-equinox/p2/assets/208716/ef5bedad-6348-459c-86d6-91b6dd192aa7)

![image](https://github.com/eclipse-equinox/p2/assets/208716/dd3f2f9e-f5d3-41c1-b756-101c4315a863)

I believe this build contains the new version with the changes:

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.40.v20230924-2142/

**Comment by merks** [comment]
Another thing that strikes me as clearly missing functionality are these unused variables:

https://github.com/eclipse/ecf/blob/dbacc2ac2671fd952a2f6b0e12277f5c63ca00ce/providers/bundles/org.eclipse.ecf.provider.filetransfer.httpclientjava/src/org/eclipse/ecf/internal/provider/filetransfer/httpclientjava/ECFHttpClientFactory.java#L34-L38

This API has setters that are called but the information that's recorded is not access and not accessible:

https://github.com/eclipse/ecf/blob/dbacc2ac2671fd952a2f6b0e12277f5c63ca00ce/providers/bundles/org.eclipse.ecf.provider.filetransfer.httpclientjava/src/org/eclipse/ecf/internal/provider/filetransfer/httpclientjava/IHttpClientContext.java#L17-L27

I think it's the replacement for this much richer API org.apache.hc.client5.http.protocol.HttpClientContext

![image](https://github.com/eclipse-equinox/p2/assets/208716/bf38a08e-aa3f-41bf-815a-6da4e9ea4bf2)

Very likely the things provided by this also need attention:

https://repo1.maven.org/maven2/org/apache/httpcomponents/client5/httpclient5-win/5.2.1/

I'm concerned that proxy selection and proxy authentication likely no longer work.

**Comment by laeubi** [comment]
Instead of being scared about missing functionality I preference to follow [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principle. So if someone needs any of those we will get a feedback and can decide if they should simply install http5 impl or now one will complain and we have saved some maintenance efforts (especially if there are obviously no test to cover these use-cases!).

Again here, Tycho has example for proxy support (and there is a testcase!):
https://github.com/eclipse-tycho/tycho/blob/3118388a504c2ad31def2bc7bc114066b1af944b/p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/transport/Java11HttpTransportFactory.java#L230-L243

**Comment by merks** [comment]
I'm quite certain that consumers will much prefer people who are proactive in preventing problems versus those who willfully discard functionality that has been working well for as long as p2 has existed on the premise that probably no one is using it, ergo no one really needs it.  The attitude that this approach is principle-based virtue feels a little like salt in a wound.  Of course when one develops something new, one can (and perhaps should) avoid providing something not proven to be needed, but this here in this case is functionality that worked well before.
 
Consider the fact that that once someone discovers they cannot update or install anymore, they **cannot** install the thing needed to solve the problem that they cannot install because they already cannot install.   Also, the installer, when it fails to function, doesn't have the option to install something that does work.   

Also consider that it's not demonstrated which implementation takes precedence when there are two.  My superficial testing (breakpoints) suggest the httpjavaclient continues to be used when both are installed:

![image](https://github.com/eclipse-equinox/p2/assets/208716/868d50bf-6d1e-4807-ae5e-edf01c6caa40)

In any case, this discussion is not likely to go in a good direction if we go further down this direction.

The lack of tests is certainly extremely disconcerting  That lack is a preexisting condition which we can point to as the primary contributing factor to this problem.  Clearly if the tests need it we are definitely going to need it, but right now the tests don't need it, leaving things open for doubt.

**Comment by laeubi** [comment]
> I'm quite certain that consumers will much prefer people who are proactive in preventing problems

I'm quite sure such people would prefer to be paid for their work proactive :-)

> consider the fact that that once someone discovers they cannot update or install anymore, they cannot install the thing needed to solve the problem that they cannot install because they already cannot install.

There is always a way e.g using [Sneakernet](https://en.wikipedia.org/wiki/Sneakernet).

> Also consider that it's not demonstrated which implementation takes precedence when there are two. 

Its likely more feasible to uninstall the "bad" one than to struggle with any precedence event though I remember that @scottslewis  has mentioned some way to control that.

**Comment by merks** [comment]
The "bad" new-improved version can't be uninstalled because p2's feature's require it to be installed.  Also, one can't do anything to fix the installer.  But please let's not go further down this line of reasoning.   And don't forget that we live in a glass house; everything we say is recorded for all to see for all time...

**Comment by akurtakov** [comment]
@laeubi I fully support people getting their work paid/funded! I also fully support @merks in his statement that we shouldn't be doing crappy work. 
At the end if a word gets out that the project doesn't care about stability and breaks things without careful consideration it's far more likely that people will move on rather than fund people to work on it which would become a loose-loose situation. 
Please note, I strongly believe that the project needs to get rid of old luggage (not saying that this functionality is or isn't such) in order for the project to get a better future but this has to happen within rules, investigated and explained if/when we drop things.

**Comment by merks** [comment]
Well said.  It likely it's not clear from my critiques and concerns that I too fully support the effort to evolve toward an implementation that uses the underlying functionality already present in a modern JDK.  That seems like a very good long-term strategy and it's thanks to the efforts of @laeubi that we are moving in that direction!  If we do a really good job of this, almost no one will notice (and no one will thank us)...

**Comment by HannesWell** [comment]
> I'm just trying to determine where responsibility lies because I get the sense that all of this ends up on my plate even though I never ordered this dish...

That's probably a greeting from the kitchen.

> I believe this build contains the new version with the changes:
> 
> https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.40.v20230924-2142/

We use a basic user+password authentication encoded in the URL in the form `https://user:password@foo.bar.org/updatesite/` and that does not work anymore with the httpclientjava, even with the most recent fix.
![grafik](https://github.com/eclipse-equinox/p2/assets/44067969/da7a46b8-ed65-42ae-82c0-522950bcfaa9)

The repository simply cannot be found:
```
org.eclipse.equinox.p2.core.ProvisionException: No repository found at https://user:password@foo.bar.org/updatesite/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:405)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:709)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.basicRefreshRepository(AbstractRepositoryManager.java:205)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.refreshRepository(ArtifactRepositoryManager.java:136)
	at org.eclipse.equinox.p2.ui.RepositoryManipulationPage.lambda$17(RepositoryManipulationPage.java:596)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

I also tried it with the 4.29 SDK and there the repository can be loaded.

Additionally I also tried Christoph's test repo with encoded credentials: `https://test:test@sslsites.de/pps.laeubi-soft.de/`
In 4.29 the repo is just loaded and in the current I-build SDK with latest `httpclientjava` the dialog to enter the credentials pops up and when I enter them again it loads successfully (so that part seems to be fixed. Thanks for that :) ).
But it looks like encoded credentials are not yet considered.
Furthermore I wonder why the dialog did not pop up for our server. Maybe a different server configuration, but if I try to access the URL without credentials in the Browser it asks for them.

**Comment by laeubi** [comment]
> But it looks like encoded credentials are not yet considered.

"Encoding" credentials in the URL is especially a major security risk so I'm not sure its good to support this anyways. Nerveless it*might* be possible to support this not in the transport but in P2 directly that brings up the dialog to check the URI but as said, **encoding plain text credential is strongly discouraged**.

**Comment by HannesWell** [comment]
> > But it looks like encoded credentials are not yet considered.
> 
> "Encoding" credentials in the URL is especially a major security risk so I'm not sure its good to support this anyways. Nerveless it_might_ be possible to support this not in the transport but in P2 directly that brings up the dialog to check the URI but as said, **encoding plain text credential is strongly discouraged**.

Can you explain this in more detail, especially why this is more risky than typing in the credentials manually?
According to [Wikipedia (and others)](https://en.wikipedia.org/wiki/Basic_access_authentication#Security) `basic authentication is typically used in conjunction with HTTPS to provide confidentiality.`
Of course it makes it a bit simpler to share the credentials with the link, but one can also share credentials and since this is standard HTTP, users can even simply assemble a URL with encoded credentials by themself if they have the URL and username+password.

And looking at the patch in ECF this is how username+password is transmitted:
https://github.com/eclipse/ecf/blob/dbacc2ac2671fd952a2f6b0e12277f5c63ca00ce/providers/bundles/org.eclipse.ecf.provider.filetransfer.httpclientjava/src/org/eclipse/ecf/provider/filetransfer/httpclientjava/HttpClientFileSystemBrowser.java#L317-L322

So why is this suddenly a major security risk if the credentials are encoded directly?

**Comment by laeubi** [comment]
> we shouldn't be doing crappy work.

I don't said we should do any "crappy" things and given the implementation is new and **completely based on volunteer efforts** it works (from my point of view) already good, so I won't qualify it as "crap" if it does not support (yet) some things that are not tested and no one knows if such features are actually used.

So if we would have upgraded to a new hypothetical http5-apache version who has verified tested all these unknown use-cases? For me everything that is not covered by an automatic test has an intrinsic risk of failing unnoticed, and unless someone do the testing itself (like I did for basic auth) or we get some platform-test engineers to do regular manual test this is simply a matter of fact.

> Can you explain this in more detail, especially why this is more risky than typing in the credentials manually?

Because your credentials appear unencoded at various places, e.g. logfiles, in the update site dialog in error messages or even worse in your version control repository pushed to the public by accident. So everyone with read access to your workspace might be able to see it or extract it from some temporary files stored on your system. If used in a browser it even appears in your browser history...

In contrast, the dialog *should* clear the password afterwards and only store it at secure places (namely the eclipse secure storage) so at best it is only visible for a very short time in process memory.

> basic authentication is typically used in conjunction with HTTPS to provide confidentiality.

Correct, basic auth should never be used without transport security.

> So why is this suddenly a major security risk if the credentials are encoded directly?

It is not *suddenly* a risk it always was is and will be a major security risk and [according to this link](https://neilmadden.blog/2019/01/16/can-you-ever-safely-include-credentials-in-a-url/) is deprecated since back in 2005.

**Comment by akurtakov** [comment]
> > we shouldn't be doing crappy work.
> 
> I don't said we should do any "crappy" things and given the implementation is new and **completely based on volunteer efforts** it works (from my point of view) already good, so I won't qualify it as "crap" if it does not support (yet) some things that are not tested and no one knows if such features are actually used.
> 

My bad. I've obviously forgotten to start with smth like "This is general reply about overall attitude towards changes not about this particular one." and "doing crappy work(not saying that this functionality is)". 
I really hope that people give me some doubt and read my replies a bit more generic as I really do reply to 10+ such threads per day and this leads to quite often failing at using the 100% correct words esp. considering that I use English only for work duties and have to use it for other things not more than several times per year.

**Comment by laeubi** [comment]
> My bad

No need to feel bad, I just wanted to say that we should not think anything might be "crap" just ist cannot fulfill _everyone needs_ ... even though its of course good to have this as a goal.

**Comment by scottslewis** [comment]
> Its likely more feasible to uninstall the "bad" one than to struggle with any precedence event though I remember that @scottslewis has mentioned some way to control that.

Yes.  There is a priority mechanism (in provider extension point) such that the higher priority (generally newer) provider will be used.

There is also a way to disable installed providers via system properties (e.g. so that users can/could use httpclient5 rather than javahttpclient *if it's present/installed*).

**Comment by HannesWell** [comment]
> > Can you explain this in more detail, especially why this is more risky than typing in the credentials manually?
> 
> Because your credentials appear unencoded at various places, e.g. logfiles, in the update site dialog in error messages or even worse in your version control repository pushed to the public by accident. So everyone with read access to your workspace might be able to see it or extract it from some temporary files stored on your system. If used in a browser it even appears in your browser history...
> 
> In contrast, the dialog _should_ clear the password afterwards and only store it at secure places (namely the eclipse secure storage) so at best it is only visible for a very short time in process memory.

For individual credentials this all makes sense, but our goal is to make the p2-repo of our product available as update-site to our users in a simple way without making it generally public. Therefore the credentials are hard-coded in the update-URL of the product-definition so that the product can get updates as if the repo where public. Of course the credentials are then visible in the scm, logs, etc. but everyone with access to the company network has access to it any way. Furthermore our users get these credentials for the first download so they are known to them any ways as well. Of course it is always possible that one shares the credentials with someone that shouldn't get them, but that can happen regardless of if they are hard-coded or individual or not.
And since these credentials only give read access to a p2-repo the worst thing that can happen is that someone unauthorized can read from the repo. But one cannot change anything or get access to private/personal data or alike.

Of course one should never to the same for individual credentials, but in this case it seemed to be ok.
But out of curiosity, what other means does P2 provide to get access to private repos, if one is not in the same network? I have to admit I don't know know much about that.

Can one estimate if the problem is likely in P2 or in ECF? I assume it is likely in ECF because on the P2 side nothing much changed.
I would be glad to provide a PR to implement that functionality also for the java-http client.

**Comment by mickaelistria** [comment]
I believe the problem is in ECF. If you have a server, it would be relatively easy to create a unit-test for ECF that just tries to fetch content from your server and you should reproduce the error without p2. It would even most likely be possible to setup a Jetty server with basic user/password authentication and use it for testing (on any environment); but that part is beyond my knowledge.

**Comment by laeubi** [comment]
> For individual credentials this all makes sense, but our goal is to make the p2-repo of our product available as update-site to our users in a simple way without making it generally public. 

That goal can usually be archived by using a random has as part of the URL the security is comparable to your current approach but does not require any deprecated technologies.


> It would even most likely be possible to setup a Jetty server with basic user/password authentication and use it for testing (on any environment); but that part is beyond my knowledge.

- https://github.com/eclipse-tycho/tycho/blob/master/tycho-core/src/test/java/org/eclipse/tycho/test/util/HttpServer.java
- https://github.com/eclipse-tycho/tycho/blob/master/tycho-its/src/test/java/org/eclipse/tycho/test/target/PasswordProtectedP2RepositoryTest.java

**Comment by scottslewis** [comment]
> I believe the problem is in ECF. 

No, the missing piece here is in the p2 RepositoryTransport code.   ECF filetransfer API has a 'connect context' arg created/set by p2 that (optionally) contains a username/password for a specific uri location.  

See org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport line 109 which uses/references org.eclipse.equinox.internal.p2.repository.Credentials.forLocation.  There may be something in p2 UI or p2 API to access (set/modify) the Credentials for a given location, but I don't know what it is.

**Comment by laeubi** [comment]
> No, the missing piece here is in the p2 RepositoryTransport code. 

@scottslewis I think this is somehow a hidden feature not implemented by ECF (nor P2) previously but http5 client supporting it implicitly. But as said this is strongly discouraged and [therefore deprecated](https://www.ietf.org/rfc/rfc3986.txt):

> Use of the format "user:password" in the userinfo field is deprecated.

So one *may* obtain that information from the passed URL from the [URL#getUserInfo()](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/net/URL.html#getUserInfo()) and then use it as if it was passed by the context.

**Comment by scottslewis** [comment]
> > No, the missing piece here is in the p2 RepositoryTransport code.
> 
> @scottslewis I think this is somehow a hidden feature not implemented by ECF (nor P2) previously but http5 client supporting it implicitly. But as said this is strongly discouraged and [therefore deprecated](https://www.ietf.org/rfc/rfc3986.txt):

I'm not saying that RepositoryTransport should or shouldn't support a deprecated URI format (I'm inclined to agree with you/rfc), I'm saying that RepositoryTransport is where it would be supported, and it might already be...by original RT authors.

**Comment by merks** [comment]
I was trying to understand how/why the https://test:test@sslsites.de/pps.laeubi-soft.de/ URI works with the older implementation only to discover that it doesn't.   After some investigation I noticed that in my testing I am using a newer versions of the client5 support which refuses to process such a thing:
```
!MESSAGE Connection to https://test:test@sslsites.de/pps.laeubi-soft.de/p2.index failed on Request URI authority contains deprecated userinfo component. Retry attempt 0 started
!STACK 0
org.apache.hc.client5.http.ClientProtocolException: Request URI authority contains deprecated userinfo component
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1009)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:997)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:76)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.hc.core5.http.ProtocolException: Request URI authority contains deprecated userinfo component
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:145)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	... 5 more
```
Apparently, for your safety and comfort, that refusal is hard coded in the implementation:

![image](https://github.com/eclipse-equinox/p2/assets/208716/87107eab-fd7d-4dde-9ad0-987774620c3e)

I believe the older implementation being used and provided by ECF was just processing it as one would hope/expect.

Note that the magical system property to disable a provider is this:
```
-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclientjava
```

Note too that there was and is no special support in p2 for processing the user info.  Any such support was handled implicitly by the underlying infrastructure.  The implementation of org.eclipse.equinox.internal.p2.repository.Credentials.forLocation(URI, boolean, AuthenticationInfo) effectively just looks up credentials in the secure storage; it is not looking at the user info of the URI. 

It could be made to look for such information as in this rough approach:
```
	public static UIServices.AuthenticationInfo forLocation(URI location, boolean prompt, UIServices.AuthenticationInfo lastUsed) throws LoginCanceledException, CoreException {

		String userInfo = location.getUserInfo();
		if (userInfo != null) {
			Matcher matcher = Pattern.compile("([^:]+):([^:]+)").matcher(userInfo); //$NON-NLS-1$
			if (matcher.matches()) {
				return new UIServices.AuthenticationInfo(matcher.group(1), matcher.group(2), false);
			}
		}
```
That does actually work with the new provider implementation...

But is it best for "your safety and comfort" to do that?

**Comment by laeubi** [comment]
> I believe the older implementation being used and provided by ECF was just processing it as one would hope/expect.

That's also my guess, because of that it *might* be possible to do it in the ECF JavaHttp11 as well even though I won't recommend it and it is now no longer supported by latest http5 ....

If we do it at P2, I think its best disabled by default and can be enabled somehow like `http` vs `https` feature in recent P2 versions.

**Comment by merks** [comment]
@HannesWell 

Note that " user+password authentication encoded in the URL" will not work without additional changes:

https://github.com/eclipse-equinox/p2/issues/330#issuecomment-1736970547

What is your expectation for the eventual release supporting this or not?

**Comment by HannesWell** [comment]
> If we do it at P2, I think its best disabled by default and can be enabled somehow like `http` vs `https` feature in recent P2 versions.

Sounds fair.


> @HannesWell
> 
> Note that " user+password authentication encoded in the URL" will not work without additional changes:
> 
> [#330 (comment)](https://github.com/eclipse-equinox/p2/issues/330#issuecomment-1736970547)
> 
> What is your expectation for the eventual release supporting this or not?

I'm not yet entirely sure. On the short term we will probably use Christoph's suggestion, but on the long run basic-auth might be necessary again in case we want to use individual credentials per user.
I'll probably have a look at it some at it in the future, but from your and Scots remark I assume it is not too complicated to implement, I just have to find the right spot.
