### ISSUE TITLE
Error log message: beginTask should only be called once per instance. At least call done() before further invocations on install

### ISSUE THREAD

**Issue by ajohnson1** [eclipse-equinox/p2#335]
This was seen on a development version of Eclipse Memory Analyzer built against an Eclipse 4.30-I-build.

eclipse.buildId=unknown
java.fullversion=17.0.6+10
JRE 17 Windows 11 amd64-64-Bit Compressed References 20230117_367 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.jface
Warning
Mon Sep 25 18:25:19 BST 2023
beginTask should only be called once per instance. At least call done() before further invocations

java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:148)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:449)
	at org.eclipse.equinox.internal.p2.director.SimplePlanner.getProvisioningPlan(SimplePlanner.java:516)
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:329)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ProvisioningOperationWizard.lambda$10(ProvisioningOperationWizard.java:346)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: beginTask(, 1000) was called here previously
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:155)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:449)
	at org.eclipse.equinox.internal.p2.operations.PlannerResolutionJob.runModal(PlannerResolutionJob.java:75)
	at org.eclipse.equinox.p2.operations.ProfileChangeOperation.resolveModal(ProfileChangeOperation.java:118)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ProvisioningOperationWizard.lambda$10(ProvisioningOperationWizard.java:343)
	... 1 more

Also reproducible from 
https://download.eclipse.org/eclipse/downloads/drops4/I20230924-0600/

**Comment by vogella** [comment]
cc @jukzi @iloveeclipse

**Comment by jukzi** [comment]
org.eclipse.equinox.p2.operations.ProfileChangeOperation.resolveModal(IProgressMonitor)
passes monitor to both makeResolveJob() and runModal(). That does not make sense and is forbidden by javadoc. Before passing it to multiple consumers that monitor has to be splitted. I'l create a PR. @ajohnson1 please describe which steps are neseesary to reproduce the issue

**Comment by jukzi** [comment]
Reproducible with org.eclipse.equinox.p2.tests.ui.dialogs.InstallWizardTest.testInstallWizardResolved()

**Comment by vogella** [comment]
I also see such an error entry for nightly EGit, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=582511
