### ISSUE TITLE
URISyntaxException

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/p2#361]
running help/Perform Setup Tasks... in an oomphed platform workspace results in

```
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while unconfiguring the items to uninstall
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:578)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:359)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=C__Users_jkubitz_platform-2023-10-23_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Unconfigure, operand=[R]org.eclipse.sdk.ide.executable.win32.win32.x86_64.eclipse 4.30.0.I20231022-1800 --> null, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.SetLauncherNameAction).
  ERROR: org.eclipse.equinox.p2.engine code=0 java.net.URISyntaxException: Illegal character in scheme name at index 0: %23C:%5CProgram%20Files%5CEclipse%20Adoptium%5Cjdk-17.0.8.101-hotspot%5Cbin
  java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in scheme name at index 0: %23C:%5CProgram%20Files%5CEclipse%20Adoptium%5Cjdk-17.0.8.101-hotspot%5Cbin
    at org.eclipse.core.runtime.URIUtil.append(URIUtil.java:91)
    at org.eclipse.core.runtime.URIUtil.makeAbsolute(URIUtil.java:471)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EclipseLauncherParser.getVM(EclipseLauncherParser.java:110)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EclipseLauncherParser.read(EclipseLauncherParser.java:82)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxManipulatorImpl.loadWithoutFwPersistentData(EquinoxManipulatorImpl.java:395)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxManipulatorImpl.load(EquinoxManipulatorImpl.java:368)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.LazyManipulator.loadDelegate(LazyManipulator.java:60)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.LazyManipulator.getLauncherData(LazyManipulator.java:129)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.SetLauncherNameAction.setLauncher(SetLauncherNameAction.java:53)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.SetLauncherNameAction.execute(SetLauncherNameAction.java:37)
    at org.eclipse.equinox.internal.p2.engine.ParameterizedProvisioningAction.execute(ParameterizedProvisioningAction.java:42)
    at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:186)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:99)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
    at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:48)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:574)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:359)
    at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: %23C:%5CProgram%20Files%5CEclipse%20Adoptium%5Cjdk-17.0.8.101-hotspot%5Cbin
    at java.base/java.net.URI$Parser.fail(URI.java:2963)
    at java.base/java.net.URI$Parser.checkChars(URI.java:3134)
    at java.base/java.net.URI$Parser.checkChar(URI.java:3144)
    at java.base/java.net.URI$Parser.parse(URI.java:3159)
    at java.base/java.net.URI.<init>(URI.java:713)
    at java.base/java.net.URI.<init>(URI.java:814)
    at org.eclipse.core.runtime.URIUtil.append(URIUtil.java:69)
    at org.eclipse.core.runtime.URIUtil.makeAbsolute(URIUtil.java:471)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EclipseLauncherParser.getVM(EclipseLauncherParser.java:110)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EclipseLauncherParser.read(EclipseLauncherParser.java:82)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxManipulatorImpl.loadWithoutFwPersistentData(EquinoxManipulatorImpl.java:395)
    at org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxManipulatorImpl.load(EquinoxManipulatorImpl.java:368)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.LazyManipulator.loadDelegate(LazyManipulator.java:60)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.LazyManipulator.getLauncherData(LazyManipulator.java:129)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.SetLauncherNameAction.setLauncher(SetLauncherNameAction.java:53)
    at org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.SetLauncherNameAction.execute(SetLauncherNameAction.java:37)
    at org.eclipse.equinox.internal.p2.engine.ParameterizedProvisioningAction.execute(ParameterizedProvisioningAction.java:42)
    at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:186)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:99)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
    at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:48)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:574)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:359)
    at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
    ... 1 more

```

![image](https://github.com/eclipse-equinox/p2/assets/51790620/b160c33f-cbde-4fb9-bd7a-ab7cb057f225)

**Comment by jukzi** [comment]
i have an uncommented line like that in the eclipse.ini:
![image](https://github.com/eclipse-equinox/p2/assets/51790620/46c0a05c-5e43-4d57-b8ec-75e81d7c91c3)

**Comment by laeubi** [comment]
> i have an uncommented line like that in the eclipse.ini:

I don't think `eclipse.ini` supports comments...

**Comment by jukzi** [comment]
https://en.wikipedia.org/wiki/INI_file
and it works, when starting eclipse :-)

**Comment by iloveeclipse** [comment]
> I don't think `eclipse.ini` supports comments...

Not middle in the `-vm` argument handling, that expects url on **next line**.

**Comment by jukzi** [comment]
it started with jdk 20 and configuration does not say anything about 17:
![image](https://github.com/eclipse-equinox/p2/assets/51790620/b3de17d4-63f3-4945-997e-05f9dd58ab48)

**Comment by laeubi** [comment]
> https://en.wikipedia.org/wiki/INI_file and it works, when starting eclipse :-)

Even if Eclipse would support **that** ini file syntax the page says:

>> [Semicolons](https://en.wikipedia.org/wiki/Semicolon) (;) at the beginning of the line indicate a [comment](https://en.wikipedia.org/wiki/Comment_(computer_programming)).

**Comment by merks** [comment]
One would hope and expect expect that that this then removes comment lines, whatever the syntax might be:

org.eclipse.equinox.internal.frameworkadmin.equinox.utils.FileUtils.loadFile(File)

**Comment by jukzi** [comment]
read the full document
![image](https://github.com/eclipse-equinox/p2/assets/51790620/5cad67db-bffe-4b11-8615-d1deebc3400a)

**Comment by merks** [comment]
Can we find where the *.ini is being read at runtime to make sure we do the same thing?  Maybe that happens in the native code I guess.   :-(

**Comment by laeubi** [comment]
> read the full document

please read it carefully

>> **Some Software** supports

@merks  the `-vm` is evaluated very early because it configures the VM to start Eclipse itself, I think you need to look at the native launcher code how its handled there, but we have some code duplication the obviously as well...

**Comment by merks** [comment]
This reminds me a little of a joke where the patient says "Doctor, doctor, it hurts when I do this" and the doctor's reply is, "So don't do this."  😱

**Comment by jukzi** [comment]
i am not the only one who uses # comments in eclipse.ini see
https://stackoverflow.com/questions/6137429/is-it-possible-to-add-comments-to-eclipse-ini-file

**Comment by jukzi** [comment]
there is even an explanation:
the ini file is loaded with
org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser.loadProperties(File)
and that uses java.util.Properties.load(InputStream) which interprets "#" as comment by specification

**Comment by merks** [comment]
This might also be a case of "discussing" the problem taking longer than fixing it.  Unless of course one is hoping to discuss someone else into fixing it.   😱

**Comment by jukzi** [comment]
Can we agree that "#" should be uniformly interpreted as comment line? Then i could propose a patch

**Comment by merks** [comment]
Oh, and don't confuse reading the config.ini (a properties files) with the <product>.ini (definitely no a properties file).

I think it's safe to assume that any line that starts with optional whitespace followed by a # could be ignored because one can't think of it having any other meaning...

**Comment by merks** [comment]
@jukzi 

Can this issue be closed now?

**Comment by jukzi** [comment]
> Can this issue be closed now?

yes its fixed.
