### ISSUE TITLE
Random failing SharedInstallTests

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/p2#571]
https://download.eclipse.org/eclipse/downloads/drops4/I20241120-1800/testresults/html/org.eclipse.equinox.p2.tests_ep434I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertFalse(Assert.java:39)
at junit.framework.Assert.assertFalse(Assert.java:47)
at junit.framework.TestCase.assertFalse(TestCase.java:216)
at org.eclipse.equinox.p2.tests.reconciler.dropins.SharedInstallTests.testReadOnlyDropinsStartup(SharedInstallTests.java:140)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.equinox.p2.tests.AbstractProvisioningTest.runTest(AbstractProvisioningTest.java:968)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.equinox.p2.tests.reconciler.dropins.ReconcilerTestSuite.run(ReconcilerTestSuite.java:87)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)

```

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20241127-1240/testresults/html/org.eclipse.equinox.p2.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

**Comment by jukzi** [comment]
failed again:
https://download.eclipse.org/eclipse/downloads/drops4/I20241209-1800/testresults/html/org.eclipse.equinox.p2.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

**Comment by trancexpress** [comment]
Another fail in the same test case: https://download.eclipse.org/eclipse/downloads/drops4/I20260330-0010/testresults/html/org.eclipse.equinox.p2.tests_ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
N/A

junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertFalse(Assert.java:39)
at junit.framework.Assert.assertFalse(Assert.java:47)
at junit.framework.TestCase.assertFalse(TestCase.java:216)
at org.eclipse.equinox.p2.tests.reconciler.dropins.SharedInstallTests.testUserDropinsStartup(SharedInstallTests.java:187)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.equinox.p2.tests.AbstractProvisioningTest.runTest(AbstractProvisioningTest.java:989)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.equinox.p2.tests.reconciler.dropins.ReconcilerTestSuite.run(ReconcilerTestSuite.java:91)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236)
```

**Comment by trancexpress** [comment]
And another fail: https://download.eclipse.org/eclipse/downloads/drops4/I20260915-2300/testresults/html/org.eclipse.equinox.p2.tests_ep442I-unit-linux-x86_64-java25_linux.gtk.x86_64_25.html

```
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertFalse(Assert.java:39)
at junit.framework.Assert.assertFalse(Assert.java:47)
at junit.framework.TestCase.assertFalse(TestCase.java:216)
at org.eclipse.equinox.p2.tests.reconciler.dropins.SharedInstallTests.testReadOnlyDropinsStartup(SharedInstallTests.java:148)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at junit.framework.TestCase.runTest(TestCase.java:177)
at org.eclipse.equinox.p2.tests.AbstractProvisioningTest.runTest(AbstractProvisioningTest.java:989)
at junit.framework.TestCase.runBare(TestCase.java:142)
at junit.framework.TestResult$1.protect(TestResult.java:122)
at junit.framework.TestResult.runProtected(TestResult.java:142)
at junit.framework.TestResult.run(TestResult.java:125)
at junit.framework.TestCase.run(TestCase.java:130)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at org.eclipse.equinox.p2.tests.reconciler.dropins.ReconcilerTestSuite.run(ReconcilerTestSuite.java:91)
at junit.framework.TestSuite.runTest(TestSuite.java:241)
at junit.framework.TestSuite.run(TestSuite.java:236) 
```
